### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by james7132** [RomanZhu/FixedPoint-Sharp#3]
The README does not document the following:

 * What is the effective range? -2^47 to 2^47?
 * What overflow behaviors are expected? Does it work with `checked`/`unchecked` blocks?
 * Are conversions to other numeric types explicit/implicit?

**Comment by Vincenz099** [comment]
Due to the optimisation for speed, the muls and divs are significantly faster, but use the whole range of 32 bits to overflow into, meaning its only having a range of -2^15 to +2^15 and -Q15.16 to +Q15.16
Overflow is as described above.

**Comment by RomanZhu** [comment]
Conversions to other numeric types are explicit: https://github.com/RomanZhu/FixedPoint-Sharp/blob/8bbcc9d3523277035f2cc3fc026264bdc4f9901b/FixedPointSharp/fixnum/fp.cs#L278
All basic operations also accept ints: https://github.com/RomanZhu/FixedPoint-Sharp/blob/8bbcc9d3523277035f2cc3fc026264bdc4f9901b/FixedPointSharp/fixnum/fp.cs#L96
