### ISSUE TITLE
fixmath.Cos function is not working correctly

### ISSUE THREAD

**Issue by hyamw** [RomanZhu/FixedPoint-Sharp#4]
Try use -Math.PI*2 as parameter, it will throw an exception.

**Comment by RomanZhu** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/12017366/101611842-4cf2da00-3a0a-11eb-8980-0d7ab6585ec6.png)
Can't reproduce

You can read the method signature to see that this method accepts only fp type, not double/float.

**Comment by hyamw** [comment]
Sorry, I made a mistake. the testing code is here:

```
const float EPSILON = 0.0001f;
        static float Lerp(float min, float max, float t)
        {
            return (max - min) * t + min;
        }

        static void CosFixnum(float v)
        {
            try
            {
                float expected = (float)Math.Cos(v);
                fp m = fp.ParseUnsafe(v);
                float real = fixmath.Cos(m).AsFloat;
                if (Math.Abs(expected - real) > EPSILON)
                {
                    Console.WriteLine($"Cos.Fixnum error, input={v}, expected={expected}, real={real}, diff={expected - real}");
                }
            }
            catch (System.Exception ex)
            {
                Console.WriteLine($"Cos.Fixnum error: {ex.ToString()}, value:{v}");
            }
        }

        static void Main(string[] args)
        {
            int COUNT = 1000;
            float min = (float)-Math.PI * 2;
            float max = (float)Math.PI * 2;

            for (int i = 0; i < COUNT; i++)
            {
                float current = Lerp(min, max, i / (float)(COUNT - 1));
                CosFixnum(current);
            }
        }
```

with the testing code, the first error input value is -6.270607

**Comment by RomanZhu** [comment]
with the approach I have (lerping 2 values from LUT) max precision is 0.001
it reduces the LUT size to a few kb in size, but limits the precision

originally I had LUT entry for each possible FP value, but that was ~10mb in size

such loss of precision is worth it to me, but since it's an open-source library - you can change it back and write your own LUT generator

**Comment by hyamw** [comment]
Precision is not a problem. The issue is it will throw exception when I run the test code. I think that's not expected.

**Comment by RomanZhu** [comment]
Thanks for finding it out, pushed the fix
